name: "mapkubeapis"
version: "0.0.1"
usage: "map release deprecated Kubernetes APIs in-place"
description: "map release deprecated Kubernetes APIs in-place"
command: "$HELM_PLUGIN_DIR/bin/mapkubeapis"
