mappings:
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1\nkind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: Deployment"
    newAPI: "apiVersion: apps/v1\nkind: Deployment"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1\nkind: StatefulSet"
    newAPI: "apiVersion: apps/v1\nkind: StatefulSet"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: StatefulSet"
    newAPI: "apiVersion: apps/v1\nkind: StatefulSet"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: DaemonSet"
    newAPI: "apiVersion: apps/v1\nkind: DaemonSet"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: DaemonSet"
    newAPI: "apiVersion: apps/v1\nkind: DaemonSet"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta1\nkind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apps/v1beta2\nkind: ReplicaSet"
    newAPI: "apiVersion: apps/v1\nkind: ReplicaSet"
    deprecatedInVersion: "1.9"
    removedInVersion: "1.16"
  - deprecatedAPI: "extensions/v1beta1\nkind: NetworkPolicy"
    newAPI: "apiVersion: networking.k8s.io/v1\nkind: NetworkPolicy"
    deprecatedInVersion: "1.8"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: PodSecurityPolicy"
    newAPI: "apiVersion: policy/v1beta1\nkind: PodSecurityPolicy"
    deprecatedInVersion: "1.10"
    removedInVersion: "1.16"
  - deprecatedAPI: "apiVersion: apiextensions.k8s.io/v1beta1\nkind: CustomResourceDefinition"
    newAPI: "apiVersion: apiextensions.k8s.io/v1\nkind: CustomResourceDefinition"
    deprecatedInVersion: "1.16"
    removedInVersion: "1.19"
  - deprecatedAPI: "apiVersion: extensions/v1beta1\nkind: Ingress"
    newAPI: "apiVersion: networking.k8s.io/v1beta1\nkind: Ingress"
    deprecatedInVersion: "1.14"
    removedInVersion: "1.22"

  # Do NOT enable this prior to Kubernetes v1.17
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRole"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRoleList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRoleBinding"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: ClusterRoleBindingList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBindingList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: Role"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: Role"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: RoleList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: RoleBinding"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1alpha1\nkind: RoleBindingList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBindingList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta\nkind: ClusterRole"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRole"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRoleList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRoleBinding"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: ClusterRoleBindingList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBindingList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: Role"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: Role"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: RoleList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: RoleBinding"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
  # - deprecatedAPI: "apiVersion: rbac.authorization.k8s.io/v1beta1\nkind: RoleBindingList"
  #   newAPI: "apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBindingList"
  #   deprecatedInVersion: "1.17"
  #   removedInVersion: "1.22"
